### ISSUE TITLE
Hello, Lothiraldan, I can't compile npm

### ISSUE THREAD

**Issue by net592** [Lothiraldan/saltpad#138]
**My environment**
[root@hdfs02 saltpad]# node -v
v0.10.42
[root@hdfs02 saltpad]# npm -v
3.7.2
[root@hdfs02 saltpad]# cat /etc/redhat-release 
CentOS release 6.5 (Final)

Try to test, and failure
[root@hdfs02 saltpad]# npm install              
saltpad@ /opt/saltpad
├── **UNMET PEER DEPENDENCY browserify@>=3.28.0 <=4.x**
├─┬ mapify@0.1.0 
│ └─┬ glob@3.2.11 
│   └─┬ minimatch@0.3.0 
│     ├── lru-cache@2.7.3 
│     └── sigmund@1.0.1 
└─┬ standard@4.5.4
  └─┬ standard-format@1.6.10
    └─┬ esformatter@0.8.2
      └─┬ npm-run@2.0.0
        └─┬ spawn-sync@1.0.15
          └─┬ try-thread-sleep@1.0.0
            └─┬ thread-sleep@1.0.4
              └─┬ node-pre-gyp@0.6.9
                └─┬ tar-pack@2.0.0
                  └─┬ fstream-ignore@0.0.7
                    └─┬ minimatch@0.2.14
                      └── sigmund@1.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN **mapify@0.1.0 requires a peer of browserify@>=3.28.0 <=4.x but none was installed.**
npm WARN saltpad@ No license field.

**[root@hdfs02 saltpad]# npm start**
 [573] ./app/services/auto_updater.js 2.43 kB {0} [built]

ERROR in .**/~/css-loader!./app/assets/css/style-responsive.css
Module build failed: ReferenceError: Promise is not defined**
    at LazyResult.async (/opt/saltpad/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/opt/saltpad/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/opt/saltpad/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/opt/saltpad/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/assets/css/style-responsive.css 4:14-93 13:2-17:4 14:20-99

node.js version ?
A novice...., thank you for your project!

**Comment by Lothiraldan** [comment]
Could you try with a more recent version of node?

You don't need to install node, npm, node dependency and bower dependency if you just want to test saltpad, you only need to launch the vagrant image located in vagrant directory.

**Comment by Lothiraldan** [comment]
I think you hit this bug: https://github.com/webpack/css-loader/issues/144

**Comment by net592** [comment]
Thank you very much，I try 0.12.x @Lothiraldan

**Comment by Lothiraldan** [comment]
Any news @net592? If it worked, could you please close the issue?

**Comment by Lothiraldan** [comment]
@net592 Someone else hit the same bug, did installing a new version of node helped?
