### ISSUE TITLE
Error: Cannot find module 'express' during saltpad startup in devServer.js

### ISSUE THREAD

**Issue by onorua** [Lothiraldan/saltpad#183]
### what I have:
- GNU/Linux Debian system with kernel `Linux 4.7.0-1-amd64`
- Docker `1.12.1`
- docker-compose version `1.8.0`

### what I've got
I'm following documentation for running saltpad with docker, and during startup I get following error:
```
docker-compose up saltpad
Starting saltpad_saltpad_1
Attaching to saltpad_saltpad_1
saltpad_1   | npm info it worked if it ends with ok
saltpad_1   | npm info using npm@3.10.6
saltpad_1   | npm info using node@v6.5.0
saltpad_1   | npm info lifecycle saltpad@~prestart: saltpad@
saltpad_1   | npm info lifecycle saltpad@~start: saltpad@
saltpad_1   | 
saltpad_1   | > saltpad@ start /usr/src/app
saltpad_1   | > node devServer.js
saltpad_1   | 
saltpad_1   | module.js:457
saltpad_1   |     throw err;
saltpad_1   |     ^
saltpad_1   | 
saltpad_1   | Error: Cannot find module 'express'
saltpad_1   |     at Function.Module._resolveFilename (module.js:455:15)
saltpad_1   |     at Function.Module._load (module.js:403:25)
saltpad_1   |     at Module.require (module.js:483:17)
saltpad_1   |     at require (internal/module.js:20:19)
saltpad_1   |     at Object.<anonymous> (/usr/src/app/devServer.js:2:15)
saltpad_1   |     at Module._compile (module.js:556:32)
saltpad_1   |     at Object.Module._extensions..js (module.js:565:10)
saltpad_1   |     at Module.load (module.js:473:32)
saltpad_1   |     at tryModuleLoad (module.js:432:12)
saltpad_1   |     at Function.Module._load (module.js:424:3)
saltpad_1   | 
saltpad_1   | npm info lifecycle saltpad@~start: Failed to exec start script
saltpad_1   | npm ERR! Linux 4.7.0-1-amd64
saltpad_1   | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
saltpad_1   | npm ERR! node v6.5.0
saltpad_1   | npm ERR! npm  v3.10.6
saltpad_1   | npm ERR! code ELIFECYCLE
saltpad_1   | npm ERR! saltpad@ start: `node devServer.js`
saltpad_1   | npm ERR! Exit status 1
saltpad_1   | npm ERR! 
saltpad_1   | npm ERR! Failed at the saltpad@ start script 'node devServer.js'.
saltpad_1   | npm ERR! Make sure you have the latest version of node.js and npm installed.
saltpad_1   | npm ERR! If you do, this is most likely a problem with the saltpad package,
saltpad_1   | npm ERR! not with npm itself.
saltpad_1   | npm ERR! Tell the author that this fails on your system:
saltpad_1   | npm ERR!     node devServer.js
saltpad_1   | npm ERR! You can get information on how to open an issue for this project with:
saltpad_1   | npm ERR!     npm bugs saltpad
saltpad_1   | npm ERR! Or if that isn't available, you can get their info via:
saltpad_1   | npm ERR!     npm owner ls saltpad
saltpad_1   | npm ERR! There is likely additional logging output above.
saltpad_1   | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
saltpad_1   | 
saltpad_1   | npm ERR! Please include the following file with any support request:
saltpad_1   | npm ERR!     /usr/src/app/npm-debug.log
saltpad_saltpad_1 exited with code 1
```
### Debug information:
```
cat /usr/src/app/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.6
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle saltpad@~prestart: saltpad@
6 silly lifecycle saltpad@~prestart: no script for prestart, continuing
7 info lifecycle saltpad@~start: saltpad@
8 verbose lifecycle saltpad@~start: unsafe-perm in lifecycle true
9 verbose lifecycle saltpad@~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle saltpad@~start: CWD: /usr/src/app
11 silly lifecycle saltpad@~start: Args: [ '-c', 'node devServer.js' ]
12 silly lifecycle saltpad@~start: Returned: code: 1  signal: null
13 info lifecycle saltpad@~start: Failed to exec start script
14 verbose stack Error: saltpad@ start: `node devServer.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid saltpad@
16 verbose cwd /usr/src/app
17 error Linux 4.7.0-1-amd64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.5.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error saltpad@ start: `node devServer.js`
22 error Exit status 1
23 error Failed at the saltpad@ start script 'node devServer.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the saltpad package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node devServer.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs saltpad
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls saltpad
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I've tried to update npm from version `3.10.3` to `3.10.6` but it did not help. So I've tried to install express manually:
```
npm install express
npm info it worked if it ends with ok
npm info using npm@3.10.6
npm info using node@v6.5.0
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/express
npm info addNameTag [ 'express', 'latest' ]
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/content-disposition
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/content-type
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/cookie-signature
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/accepts
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/array-flatten
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/depd
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/encodeurl
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/debug
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/escape-html
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/etag
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/cookie
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/fresh
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/finalhandler
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/merge-descriptors
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/parseurl
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/on-finished
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/methods
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/path-to-regexp
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/range-parser
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/proxy-addr
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/send
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/utils-merge
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/serve-static
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/qs
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/vary
npm info attempt registry request try #1 at 12:56:55 PM
npm http request GET https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/content-disposition
npm http 304 https://registry.npmjs.org/cookie
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/encodeurl
npm http 304 https://registry.npmjs.org/merge-descriptors
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/array-flatten
npm http 200 https://registry.npmjs.org/escape-html
npm http 304 https://registry.npmjs.org/cookie-signature
npm http 304 https://registry.npmjs.org/finalhandler
npm http 304 https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/path-to-regexp
npm http 304 https://registry.npmjs.org/etag
npm http 200 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/send
npm http 304 https://registry.npmjs.org/serve-static
npm http 200 https://registry.npmjs.org/depd
npm http 200 https://registry.npmjs.org/range-parser
npm http 200 https://registry.npmjs.org/proxy-addr
npm http 200 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/fresh
npm http 200 https://registry.npmjs.org/utils-merge
npm http 304 https://registry.npmjs.org/vary
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/mime-types
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/mime-types
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/ms
npm http 304 https://registry.npmjs.org/ms
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/unpipe
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/statuses
npm http 304 https://registry.npmjs.org/statuses
npm http 200 https://registry.npmjs.org/unpipe
npm info attempt registry request try #1 at 12:57:00 PM
npm http request GET https://registry.npmjs.org/ee-first
npm http 304 https://registry.npmjs.org/ee-first
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/forwarded
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/ipaddr.js
npm http 304 https://registry.npmjs.org/ipaddr.js
npm http 304 https://registry.npmjs.org/forwarded
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/destroy
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/http-errors
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/destroy
npm http 200 https://registry.npmjs.org/mime
npm http 200 https://registry.npmjs.org/http-errors
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/setprototypeof
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/setprototypeof
npm http 200 https://registry.npmjs.org/inherits
npm info attempt registry request try #1 at 12:57:01 PM
npm http request GET https://registry.npmjs.org/media-typer
npm http 304 https://registry.npmjs.org/media-typer
npm info lifecycle depd@1.1.0~preinstall: depd@1.1.0
npm info lifecycle destroy@1.0.4~preinstall: destroy@1.0.4
npm info lifecycle ee-first@1.1.1~preinstall: ee-first@1.1.1
npm info lifecycle encodeurl@1.0.1~preinstall: encodeurl@1.0.1
npm info lifecycle escape-html@1.0.3~preinstall: escape-html@1.0.3
npm info lifecycle etag@1.7.0~preinstall: etag@1.7.0
npm info lifecycle forwarded@0.1.0~preinstall: forwarded@0.1.0
npm info lifecycle fresh@0.3.0~preinstall: fresh@0.3.0
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle ipaddr.js@1.1.1~preinstall: ipaddr.js@1.1.1
npm info lifecycle media-typer@0.3.0~preinstall: media-typer@0.3.0
npm info lifecycle mime@1.3.4~preinstall: mime@1.3.4
npm info lifecycle mime-db@1.23.0~preinstall: mime-db@1.23.0
npm info lifecycle mime-types@2.1.11~preinstall: mime-types@2.1.11
npm info lifecycle ms@0.7.1~preinstall: ms@0.7.1
npm info lifecycle debug@2.2.0~preinstall: debug@2.2.0
npm info lifecycle negotiator@0.6.1~preinstall: negotiator@0.6.1
npm info lifecycle on-finished@2.3.0~preinstall: on-finished@2.3.0
npm info lifecycle parseurl@1.3.1~preinstall: parseurl@1.3.1
npm info lifecycle range-parser@1.2.0~preinstall: range-parser@1.2.0
npm info lifecycle setprototypeof@1.0.1~preinstall: setprototypeof@1.0.1
npm info lifecycle statuses@1.3.0~preinstall: statuses@1.3.0
npm info lifecycle http-errors@1.5.0~preinstall: http-errors@1.5.0
npm info lifecycle send@0.14.1~preinstall: send@0.14.1
npm info lifecycle unpipe@1.0.0~preinstall: unpipe@1.0.0
npm info lifecycle accepts@1.3.3~preinstall: accepts@1.3.3
npm info lifecycle array-flatten@1.1.1~preinstall: array-flatten@1.1.1
npm info lifecycle content-disposition@0.5.1~preinstall: content-disposition@0.5.1
npm info lifecycle content-type@1.0.2~preinstall: content-type@1.0.2
npm info lifecycle cookie@0.3.1~preinstall: cookie@0.3.1
npm info lifecycle cookie-signature@1.0.6~preinstall: cookie-signature@1.0.6
npm info lifecycle finalhandler@0.5.0~preinstall: finalhandler@0.5.0
npm info lifecycle merge-descriptors@1.0.1~preinstall: merge-descriptors@1.0.1
npm info lifecycle methods@1.1.2~preinstall: methods@1.1.2
npm info lifecycle path-to-regexp@0.1.7~preinstall: path-to-regexp@0.1.7
npm info lifecycle proxy-addr@1.1.2~preinstall: proxy-addr@1.1.2
npm info lifecycle qs@6.2.0~preinstall: qs@6.2.0
npm info lifecycle serve-static@1.11.1~preinstall: serve-static@1.11.1
npm info lifecycle type-is@1.6.13~preinstall: type-is@1.6.13
npm info lifecycle utils-merge@1.0.0~preinstall: utils-merge@1.0.0
npm info lifecycle vary@1.1.0~preinstall: vary@1.1.0
npm info lifecycle express@4.14.0~preinstall: express@4.14.0
npm info linkStuff depd@1.1.0
npm info linkStuff destroy@1.0.4
npm info linkStuff ee-first@1.1.1
npm info linkStuff encodeurl@1.0.1
npm info linkStuff escape-html@1.0.3
npm info linkStuff etag@1.7.0
npm info linkStuff forwarded@0.1.0
npm info linkStuff fresh@0.3.0
npm info linkStuff inherits@2.0.1
npm info linkStuff ipaddr.js@1.1.1
npm info linkStuff media-typer@0.3.0
npm info linkStuff mime@1.3.4
npm info linkStuff mime-db@1.23.0
npm info linkStuff mime-types@2.1.11
npm info linkStuff ms@0.7.1
npm info linkStuff debug@2.2.0
npm info linkStuff negotiator@0.6.1
npm info linkStuff on-finished@2.3.0
npm info linkStuff parseurl@1.3.1
npm info linkStuff range-parser@1.2.0
npm info linkStuff setprototypeof@1.0.1
npm info linkStuff statuses@1.3.0
npm info linkStuff http-errors@1.5.0
npm info linkStuff send@0.14.1
npm info linkStuff unpipe@1.0.0
npm info linkStuff accepts@1.3.3
npm info linkStuff array-flatten@1.1.1
npm info linkStuff content-disposition@0.5.1
npm info linkStuff content-type@1.0.2
npm info linkStuff cookie@0.3.1
npm info linkStuff cookie-signature@1.0.6
npm info linkStuff finalhandler@0.5.0
npm info linkStuff merge-descriptors@1.0.1
npm info linkStuff methods@1.1.2
npm info linkStuff path-to-regexp@0.1.7
npm info linkStuff proxy-addr@1.1.2
npm info linkStuff qs@6.2.0
npm info linkStuff serve-static@1.11.1
npm info linkStuff type-is@1.6.13
npm info linkStuff utils-merge@1.0.0
npm info linkStuff vary@1.1.0
npm info linkStuff express@4.14.0
npm info lifecycle depd@1.1.0~install: depd@1.1.0
npm info lifecycle destroy@1.0.4~install: destroy@1.0.4
npm info lifecycle ee-first@1.1.1~install: ee-first@1.1.1
npm info lifecycle encodeurl@1.0.1~install: encodeurl@1.0.1
npm info lifecycle escape-html@1.0.3~install: escape-html@1.0.3
npm info lifecycle etag@1.7.0~install: etag@1.7.0
npm info lifecycle forwarded@0.1.0~install: forwarded@0.1.0
npm info lifecycle fresh@0.3.0~install: fresh@0.3.0
npm info lifecycle inherits@2.0.1~install: inherits@2.0.1
npm info lifecycle ipaddr.js@1.1.1~install: ipaddr.js@1.1.1
npm info lifecycle media-typer@0.3.0~install: media-typer@0.3.0
npm info lifecycle mime@1.3.4~install: mime@1.3.4
npm info lifecycle mime-db@1.23.0~install: mime-db@1.23.0
npm info lifecycle mime-types@2.1.11~install: mime-types@2.1.11
npm info lifecycle ms@0.7.1~install: ms@0.7.1
npm info lifecycle debug@2.2.0~install: debug@2.2.0
npm info lifecycle negotiator@0.6.1~install: negotiator@0.6.1
npm info lifecycle on-finished@2.3.0~install: on-finished@2.3.0
npm info lifecycle parseurl@1.3.1~install: parseurl@1.3.1
npm info lifecycle range-parser@1.2.0~install: range-parser@1.2.0
npm info lifecycle setprototypeof@1.0.1~install: setprototypeof@1.0.1
npm info lifecycle statuses@1.3.0~install: statuses@1.3.0
npm info lifecycle http-errors@1.5.0~install: http-errors@1.5.0
npm info lifecycle send@0.14.1~install: send@0.14.1
npm info lifecycle unpipe@1.0.0~install: unpipe@1.0.0
npm info lifecycle accepts@1.3.3~install: accepts@1.3.3
npm info lifecycle array-flatten@1.1.1~install: array-flatten@1.1.1
npm info lifecycle content-disposition@0.5.1~install: content-disposition@0.5.1
npm info lifecycle content-type@1.0.2~install: content-type@1.0.2
npm info lifecycle cookie@0.3.1~install: cookie@0.3.1
npm info lifecycle cookie-signature@1.0.6~install: cookie-signature@1.0.6
npm info lifecycle finalhandler@0.5.0~install: finalhandler@0.5.0
npm info lifecycle merge-descriptors@1.0.1~install: merge-descriptors@1.0.1
npm info lifecycle methods@1.1.2~install: methods@1.1.2
npm info lifecycle path-to-regexp@0.1.7~install: path-to-regexp@0.1.7
npm info lifecycle proxy-addr@1.1.2~install: proxy-addr@1.1.2
npm info lifecycle qs@6.2.0~install: qs@6.2.0
npm info lifecycle serve-static@1.11.1~install: serve-static@1.11.1
npm info lifecycle type-is@1.6.13~install: type-is@1.6.13
npm info lifecycle utils-merge@1.0.0~install: utils-merge@1.0.0
npm info lifecycle vary@1.1.0~install: vary@1.1.0
npm info lifecycle express@4.14.0~install: express@4.14.0
npm info lifecycle depd@1.1.0~postinstall: depd@1.1.0
npm info lifecycle destroy@1.0.4~postinstall: destroy@1.0.4
npm info lifecycle ee-first@1.1.1~postinstall: ee-first@1.1.1
npm info lifecycle encodeurl@1.0.1~postinstall: encodeurl@1.0.1
npm info lifecycle escape-html@1.0.3~postinstall: escape-html@1.0.3
npm info lifecycle etag@1.7.0~postinstall: etag@1.7.0
npm info lifecycle forwarded@0.1.0~postinstall: forwarded@0.1.0
npm info lifecycle fresh@0.3.0~postinstall: fresh@0.3.0
npm info lifecycle inherits@2.0.1~postinstall: inherits@2.0.1
npm info lifecycle ipaddr.js@1.1.1~postinstall: ipaddr.js@1.1.1
npm info lifecycle media-typer@0.3.0~postinstall: media-typer@0.3.0
npm info lifecycle mime@1.3.4~postinstall: mime@1.3.4
npm info lifecycle mime-db@1.23.0~postinstall: mime-db@1.23.0
npm info lifecycle mime-types@2.1.11~postinstall: mime-types@2.1.11
npm info lifecycle ms@0.7.1~postinstall: ms@0.7.1
npm info lifecycle debug@2.2.0~postinstall: debug@2.2.0
npm info lifecycle negotiator@0.6.1~postinstall: negotiator@0.6.1
npm info lifecycle on-finished@2.3.0~postinstall: on-finished@2.3.0
npm info lifecycle parseurl@1.3.1~postinstall: parseurl@1.3.1
npm info lifecycle range-parser@1.2.0~postinstall: range-parser@1.2.0
npm info lifecycle setprototypeof@1.0.1~postinstall: setprototypeof@1.0.1
npm info lifecycle statuses@1.3.0~postinstall: statuses@1.3.0
npm info lifecycle http-errors@1.5.0~postinstall: http-errors@1.5.0
npm info lifecycle send@0.14.1~postinstall: send@0.14.1
npm info lifecycle unpipe@1.0.0~postinstall: unpipe@1.0.0
npm info lifecycle accepts@1.3.3~postinstall: accepts@1.3.3
npm info lifecycle array-flatten@1.1.1~postinstall: array-flatten@1.1.1
npm info lifecycle content-disposition@0.5.1~postinstall: content-disposition@0.5.1
npm info lifecycle content-type@1.0.2~postinstall: content-type@1.0.2
npm info lifecycle cookie@0.3.1~postinstall: cookie@0.3.1
npm info lifecycle cookie-signature@1.0.6~postinstall: cookie-signature@1.0.6
npm info lifecycle finalhandler@0.5.0~postinstall: finalhandler@0.5.0
npm info lifecycle merge-descriptors@1.0.1~postinstall: merge-descriptors@1.0.1
npm info lifecycle methods@1.1.2~postinstall: methods@1.1.2
npm info lifecycle path-to-regexp@0.1.7~postinstall: path-to-regexp@0.1.7
npm info lifecycle proxy-addr@1.1.2~postinstall: proxy-addr@1.1.2
npm info lifecycle qs@6.2.0~postinstall: qs@6.2.0
npm info lifecycle serve-static@1.11.1~postinstall: serve-static@1.11.1
npm info lifecycle type-is@1.6.13~postinstall: type-is@1.6.13
npm info lifecycle utils-merge@1.0.0~postinstall: utils-merge@1.0.0
npm info lifecycle vary@1.1.0~postinstall: vary@1.1.0
npm info lifecycle express@4.14.0~postinstall: express@4.14.0
saltpad@ /usr/src/app
`-- express@4.14.0 
  +-- accepts@1.3.3 
  | +-- mime-types@2.1.11 
  | | `-- mime-db@1.23.0 
  | `-- negotiator@0.6.1 
  +-- array-flatten@1.1.1 
  +-- content-disposition@0.5.1 
  +-- content-type@1.0.2 
  +-- cookie@0.3.1 
  +-- cookie-signature@1.0.6 
  +-- debug@2.2.0 
  | `-- ms@0.7.1 
  +-- depd@1.1.0 
  +-- encodeurl@1.0.1 
  +-- escape-html@1.0.3 
  +-- etag@1.7.0 
  +-- finalhandler@0.5.0 
  | +-- statuses@1.3.0 
  | `-- unpipe@1.0.0 
  +-- fresh@0.3.0 
  +-- merge-descriptors@1.0.1 
  +-- methods@1.1.2 
  +-- on-finished@2.3.0 
  | `-- ee-first@1.1.1 
  +-- parseurl@1.3.1 
  +-- path-to-regexp@0.1.7 
  +-- proxy-addr@1.1.2 
  | +-- forwarded@0.1.0 
  | `-- ipaddr.js@1.1.1 
  +-- qs@6.2.0 
  +-- range-parser@1.2.0 
  +-- send@0.14.1 
  | +-- destroy@1.0.4 
  | +-- http-errors@1.5.0 
  | | +-- inherits@2.0.1 
  | | `-- setprototypeof@1.0.1 
  | `-- mime@1.3.4 
  +-- serve-static@1.11.1 
  +-- type-is@1.6.13 
  | `-- media-typer@0.3.0 
  +-- utils-merge@1.0.0 
  `-- vary@1.1.0 

npm WARN saltpad@ No license field.
npm info ok 
```
am I doing something wrong or missing something?

**Comment by onorua** [comment]
After following changes to `package.json` file
```
diff --git a/package.json b/package.json
index fad4a7b..d6efe22 100644
--- a/package.json
+++ b/package.json
@@ -17,11 +17,12 @@
     "urijs": "^1.17.0"
   },
   "devDependencies": {
-    "babel": "^5.6.14",
-    "babel-core": "^5.6.15",
+    "runtime": "^0.13.0",
+    "babel": "^5.8.38",
+    "babel-core": "^5.8.38",
     "babel-eslint": "^3.1.19",
     "babel-loader": "^5.2.2",
-    "babel-runtime": "",
+    "babel-runtime": "^6.11.6",
     "babel-plugin-react-transform": "^1.1.1",
     "babel-preset-es2015": "",
     "babel-preset-react": "",
@@ -29,9 +30,11 @@
     "es6-promise": "^2.3.0",
     "node-libs-browser": "^0.5.2",
     "node-uuid": "^1.4.3",
-    "react-transform-catch-errors": "^1.0.0",
-    "react-transform-hmr": "^1.0.1",
+    "react-transform-catch-errors": "^1.0.2",
+    "react-transform-hmr": "^1.0.4",
+    "react-transform": "^0.0.3",
     "redbox-react": "^1.2.0",
+    "react-tools": "^0.10.0",
     "react-bootstrap-table": "^1.4.0",
     "react-select": "1.0.0-beta8",
     "react-mixin": "",
@@ -49,10 +52,10 @@
     "bower": "",
     "moment": "",
     "rimraf": "^2.4.3",
-    "webpack": "",
-    "webpack-dev-middleware": "^1.2.0",
-    "webpack-hot-middleware": "^2.0.0",
-    "express": "",
+    "webpack": "^1.13.2",
+    "webpack-dev-middleware": "^1.6.1",
+    "webpack-hot-middleware": "^2.12.2",
+    "express": "^4.14.0",
     "form-urlencoded": "",
     "html-webpack-plugin": "",
     "extract-text-webpack-plugin": ">=1.0.1",
```
I've got container started up, but I still receive error message:
```
saltpad_1   | ERROR in Loader /usr/src/app/node_modules/babel/index.js?{"optional":["runtime"],"stage":0,"plugins":["react-transform"],"extra":{"react-transform":{"transforms":[{"transform":"react-transform-hmr","imports":["react"],"locals":["module"]},{"transform":"react-transform-catch-errors","imports":["react","redbox-react"]}]}}} didn't return a function
saltpad_1   |  @ multi main
```

My knowledge of nodejs is reaching the maximum, any help in how to debug or fix the issue will be highly appreciated!

**Comment by arthurlogilab** [comment]
Got hit by this too. Maybe it's the version of node that needs to be adjusted.  I see no requirements version for node or npm in the docs.

@Lothiraldan do you have an idea ?

**Comment by arthurlogilab** [comment]
With node 4.6.0 it can't build : 

```
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-linked-state-mixin@15.3.2 wants react@^15.3.2
npm ERR! peerinvalid Peer react-select@1.0.0-beta8 wants react@^0.14.0
npm ERR! peerinvalid Peer redbox-react@1.3.1 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-bootstrap-table@1.6.2 wants react@^0.14.3
```

**Comment by arthurlogilab** [comment]
npm-check-updates : 

![screenshot_2016-10-05_12-24-26](https://cloud.githubusercontent.com/assets/445200/19109705/c9bf76b4-8af6-11e6-82ac-b3b334c7043c.png)

**Comment by arthurlogilab** [comment]
trying out https://github.com/peerigon/updtr

**Comment by arthurlogilab** [comment]
I managed to build it with 
```
-    "react-addons-linked-state-mixin": "",
+    "react-addons-linked-state-mixin": "^0.14.5",
```

but then I get another error (see next issue)

**Comment by geraldhansen** [comment]
I've been running into the same problems with a new Ubuntu installation:
```
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-linked-state-mixin@15.4.0 wants react@^15.4.0
npm ERR! peerinvalid Peer react-select@1.0.0-beta8 wants react@^0.14.0
npm ERR! peerinvalid Peer redbox-react@1.3.3 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-bootstrap-table@1.6.2 wants react@^0.14.3
```

Any suggestions?
